-- ─────────────────────────────────────────────────────────────────────────────
-- CoSA — Schema Update 1  |  Run in Supabase SQL Editor in order.
-- Drops old Phase 6 tables, creates the proper schema.
-- All statements are idempotent — safe to re-run.
-- ─────────────────────────────────────────────────────────────────────────────

-- ─── Drop everything (old Phase 6 tables + any partial prior runs) ───────────
DROP TABLE IF EXISTS public.subtask_checks        CASCADE;
DROP TABLE IF EXISTS public.reschedule_queue      CASCADE;
DROP TABLE IF EXISTS public.friday_reviews        CASCADE;
DROP TABLE IF EXISTS public.timer_sessions        CASCADE;
DROP TABLE IF EXISTS public.today_task_instances  CASCADE;
DROP TABLE IF EXISTS public.task_templates        CASCADE;
DROP TABLE IF EXISTS public.completion_log        CASCADE;
DROP TABLE IF EXISTS public.task_library          CASCADE;

-- ─── 1. task_templates ───────────────────────────────────────────────────────
-- One row per task in the user's Task Library.
CREATE TABLE IF NOT EXISTS public.task_templates (
  id                          text        PRIMARY KEY,
  user_id                     uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name                        text        NOT NULL DEFAULT '',
  track                       text        NOT NULL DEFAULT 'advisors'
    CHECK (track IN ('advisors','jobSearch','ventures','networking','development','cosaAdmin')),
  time_block                  text        NOT NULL DEFAULT 'BD'
    CHECK (time_block IN ('BD','Networking','Job Search','Encore OS','Friday')),
  default_estimate_minutes    integer     NOT NULL DEFAULT 25,
  completion_type             text        NOT NULL DEFAULT 'Done'
    CHECK (completion_type IN ('Done','Done + Outcome','Partial')),
  status                      text        NOT NULL DEFAULT 'Active'
    CHECK (status IN ('Active','Paused','Archived')),
  requires_definition_of_done boolean     NOT NULL DEFAULT false,
  frequency                   text        NOT NULL DEFAULT 'Weekly'
    CHECK (frequency IN ('Daily','Weekly','Monthly','As scheduled')),
  kpi_mapping                 text        NOT NULL DEFAULT '',
  subtasks                    text        NOT NULL DEFAULT '',
  outcome_prompt              text        NOT NULL DEFAULT '',
  created_at                  timestamptz NOT NULL DEFAULT now(),
  updated_at                  timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.task_templates ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'task_templates' AND policyname = 'task_templates_own_all'
  ) THEN
    CREATE POLICY "task_templates_own_all" ON public.task_templates FOR ALL
      USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ─── 2. today_task_instances ─────────────────────────────────────────────────
-- Snapshot of deployed tasks for each day. PK is the app-generated string id.
CREATE TABLE IF NOT EXISTS public.today_task_instances (
  id                          text        PRIMARY KEY,
  user_id                     uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  scheduled_for_date          date        NOT NULL,
  queue_order                 integer     NOT NULL DEFAULT 0,
  name_snapshot               text        NOT NULL DEFAULT '',
  track_snapshot              text        NOT NULL DEFAULT 'advisors'
    CHECK (track_snapshot IN ('advisors','jobSearch','ventures','networking','development','cosaAdmin')),
  time_block_snapshot         text        NOT NULL DEFAULT 'BD'
    CHECK (time_block_snapshot IN ('BD','Networking','Job Search','Encore OS','Friday')),
  estimate_minutes_snapshot   integer     NOT NULL DEFAULT 25,
  completion_type_snapshot    text        NOT NULL DEFAULT 'Done'
    CHECK (completion_type_snapshot IN ('Done','Done + Outcome','Partial')),
  frequency_snapshot          text        NOT NULL DEFAULT 'Weekly',
  kpi_mapping_snapshot        text        NOT NULL DEFAULT '',
  subtasks_snapshot           text        NOT NULL DEFAULT '',
  outcome_prompt_snapshot     text        NOT NULL DEFAULT '',
  template_id_snapshot        text,
  requires_definition_of_done boolean     NOT NULL DEFAULT false,
  created_at                  timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.today_task_instances ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'today_task_instances' AND policyname = 'today_task_instances_own_all'
  ) THEN
    CREATE POLICY "today_task_instances_own_all" ON public.today_task_instances FOR ALL
      USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ─── 3. timer_sessions ───────────────────────────────────────────────────────
-- One row per task session. Upserted on every state change.
-- PK is a UUID generated by the app (crypto.randomUUID()).
CREATE TABLE IF NOT EXISTS public.timer_sessions (
  id                      uuid        PRIMARY KEY,
  user_id                 uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  task_instance_id        text        REFERENCES public.today_task_instances(id),
  task_name               text        NOT NULL DEFAULT '',
  track                   text        NOT NULL DEFAULT 'advisors',
  kpi_mapping             text        NOT NULL DEFAULT '',
  timer_state             text        NOT NULL DEFAULT 'Not Started',
  completion_type         text        CHECK (completion_type IN ('Done','Done + Outcome','Partial','Cancelled')),
  estimate_seconds        integer     NOT NULL DEFAULT 0,
  elapsed_seconds         integer     NOT NULL DEFAULT 0,
  pause_count             integer     NOT NULL DEFAULT 0,
  pause_duration_seconds  integer     NOT NULL DEFAULT 0,
  overrun_seconds         integer     NOT NULL DEFAULT 0,
  cancelled_seconds       integer     NOT NULL DEFAULT 0,
  outcome_achieved        boolean,
  definition_of_done      text        NOT NULL DEFAULT '',
  actual_completed        text        NOT NULL DEFAULT '',
  started_at              timestamptz,
  completed_at            timestamptz,
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.timer_sessions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'timer_sessions' AND policyname = 'timer_sessions_own_all'
  ) THEN
    CREATE POLICY "timer_sessions_own_all" ON public.timer_sessions FOR ALL
      USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ─── 4. reschedule_queue ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.reschedule_queue (
  id                   text        PRIMARY KEY,
  user_id              uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  task_name            text        NOT NULL DEFAULT '',
  track                text        NOT NULL DEFAULT 'advisors',
  time_block           text        NOT NULL DEFAULT 'BD',
  reason               text        NOT NULL DEFAULT 'cancelled'
    CHECK (reason IN ('overrun','cancelled','partial')),
  remaining_minutes    integer,
  status               text        NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending','confirmed','dismissed')),
  suggested_date       date,
  suggested_time_block text,
  confirmed_at         timestamptz,
  dismissed_at         timestamptz,
  created_at           timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.reschedule_queue ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'reschedule_queue' AND policyname = 'reschedule_queue_own_all'
  ) THEN
    CREATE POLICY "reschedule_queue_own_all" ON public.reschedule_queue FOR ALL
      USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ─── 5. friday_reviews ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.friday_reviews (
  id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  week_start       date        NOT NULL,
  week_score       text        CHECK (week_score IN ('green','yellow','red')),
  kpis_hit         integer,
  kpis_total       integer,
  q1               text,
  q2               text,
  q3               text,
  monday_intention text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, week_start)
);
ALTER TABLE public.friday_reviews ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'friday_reviews' AND policyname = 'friday_reviews_own_all'
  ) THEN
    CREATE POLICY "friday_reviews_own_all" ON public.friday_reviews FOR ALL
      USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ─── 6. subtask_checks ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.subtask_checks (
  id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  timer_session_id uuid        NOT NULL REFERENCES public.timer_sessions(id) ON DELETE CASCADE,
  subtask_index    integer     NOT NULL,
  checked          boolean     NOT NULL DEFAULT false,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.subtask_checks ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'subtask_checks' AND policyname = 'subtask_checks_own_all'
  ) THEN
    CREATE POLICY "subtask_checks_own_all" ON public.subtask_checks FOR ALL
      USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;
