import type { ReconnectContact } from "./types";

const now = new Date();
const isoDaysAgo = (days: number) =>
  new Date(now.getTime() - days * 24 * 60 * 60 * 1000).toISOString();
const isoDaysFromNow = (days: number) =>
  new Date(now.getTime() + days * 24 * 60 * 60 * 1000).toISOString();

export const MOCK_RECONNECT_CONTACTS: ReconnectContact[] = [
  {
    id: "rr-001",
    name: "Amanda Kor",
    firm: "Korn Ferry",
    title: "Senior Client Partner, Marketing Officers Practice",
    specialty: "CMO / SVP Marketing",
    source: "Both",
    tier: "TIER 1",
    strategic_score: 98,
    firm_fit_score: 97,
    practice_match_score: 99,
    recency_score: 91,
    signal_score: 96,
    strategic_recommended_approach:
      "Lead with the Fractional CMO work as evidence of operator range, then bridge to full-time transformation roles. Ask what CMO searches are stuck because the client needs a builder, not a brand steward.",
    summary_of_prior_comms:
      "Warm LinkedIn connection. Prior exchange around GTM transformation and PE-backed marketing leadership. No explicit role conversation yet.",
    outlook_history:
      "Last email thread was a short reconnect after the Agency.com alumni event. Tone was warm but not yet active.",
    linkedin_url: "https://www.linkedin.com",
    hubspot_url: "https://app.hubspot.com",
    last_contact_date: isoDaysAgo(47),
    other_contacts_at_firm: "2 others: Malik Stone, Priya Raman",
    state: {
      recruiter_id: "rr-001",
      status: "queue",
      starred: true,
      updated_at: isoDaysAgo(2),
    },
    notes: [
      {
        id: "n-001",
        recruiter_id: "rr-001",
        body: "Best opener is the executive search angle, not consulting lead-gen.",
        created_at: isoDaysAgo(12),
      },
    ],
    touches: [
      {
        id: "t-001",
        recruiter_id: "rr-001",
        channel: "linkedin",
        direction: "outbound",
        body: "Light reconnect note after alumni event.",
        created_at: isoDaysAgo(47),
      },
    ],
  },
  {
    id: "rr-002",
    name: "Marcus Delaney",
    firm: "Spencer Stuart",
    title: "Consultant, Technology Marketing",
    specialty: "B2B SaaS / PE-backed growth",
    source: "LeadDelta",
    tier: "TIER 1",
    strategic_score: 96,
    firm_fit_score: 94,
    practice_match_score: 98,
    recency_score: 88,
    signal_score: 95,
    strategic_recommended_approach:
      "Send a crisp update on the GTM Architect positioning and ask whether his current searches need a CMO who can rebuild pipeline architecture, not just manage demand gen.",
    summary_of_prior_comms:
      "Met through a mutual CMO peer. Strong fit for the $50M-$500M SaaS target band.",
    outlook_history:
      "No Outlook history found. LinkedIn is the best first channel.",
    linkedin_url: "https://www.linkedin.com",
    last_contact_date: isoDaysAgo(62),
    other_contacts_at_firm: "1 other: Elise Grant",
    state: {
      recruiter_id: "rr-002",
      status: "queue",
      starred: false,
      updated_at: isoDaysAgo(5),
    },
    notes: [],
    touches: [],
  },
  {
    id: "rr-003",
    name: "Sarah Kim",
    firm: "Russell Reynolds",
    title: "Executive Search Consultant",
    specialty: "Growth marketing leadership",
    source: "Outlook (new)",
    tier: "TIER 2",
    strategic_score: 91,
    firm_fit_score: 90,
    practice_match_score: 92,
    recency_score: 78,
    signal_score: 87,
    strategic_recommended_approach:
      "Reference the current consulting portfolio and ask for a 15-minute calibration call. Position Jason as a narrow-fit candidate for transformation roles where board pressure is already visible.",
    summary_of_prior_comms:
      "Introduced by a former TBWA contact. Replied once asking for background, then thread went quiet.",
    outlook_history:
      "Inbound reply 16 days ago: open to staying in touch and asked for updated positioning.",
    linkedin_url: "https://www.linkedin.com",
    last_contact_date: isoDaysAgo(16),
    other_contacts_at_firm: "3 others: Jonah Lee, Noelle Pierce, Aaron Wu",
    state: {
      recruiter_id: "rr-003",
      status: "queue",
      starred: true,
      updated_at: isoDaysAgo(1),
    },
    notes: [
      {
        id: "n-003",
        recruiter_id: "rr-003",
        body: "Follow-up should include the tighter CMO/SVP target, not the broader advisor pitch.",
        created_at: isoDaysAgo(8),
      },
    ],
    touches: [
      {
        id: "t-003",
        recruiter_id: "rr-003",
        channel: "email",
        direction: "inbound",
        body: "Asked for current positioning.",
        created_at: isoDaysAgo(16),
      },
    ],
  },
  {
    id: "rr-004",
    name: "Noah Basu",
    firm: "Heidrick & Struggles",
    title: "Partner, Digital Officers Practice",
    specialty: "Digital transformation / GTM",
    source: "Both",
    tier: "TIER 2",
    strategic_score: 89,
    firm_fit_score: 86,
    practice_match_score: 91,
    recency_score: 82,
    signal_score: 84,
    strategic_recommended_approach:
      "Do not pitch availability cold. Ask for market calibration around CMO roles where AI-led GTM transformation is becoming board-level, then offer a concise background if relevant.",
    summary_of_prior_comms:
      "Weak tie via LinkedIn. Good firm fit, less direct warmth than Tier 1 contacts.",
    outlook_history: "No prior email thread found.",
    linkedin_url: "https://www.linkedin.com",
    last_contact_date: undefined,
    other_contacts_at_firm: "2 others: Carmen Vale, Stefan Ortega",
    state: {
      recruiter_id: "rr-004",
      status: "queue",
      starred: false,
      updated_at: isoDaysAgo(3),
    },
    notes: [],
    touches: [],
  },
  {
    id: "rr-005",
    name: "Elise Grant",
    firm: "Spencer Stuart",
    title: "Associate, CMO Practice",
    specialty: "Marketing leadership research",
    source: "LeadDelta",
    tier: "TIER 3",
    strategic_score: 82,
    firm_fit_score: 84,
    practice_match_score: 80,
    recency_score: 70,
    signal_score: 76,
    strategic_recommended_approach:
      "Move to watch unless she posts a live search. Useful bridge into Spencer Stuart, but lower immediate priority than Marcus Delaney.",
    summary_of_prior_comms: "No direct history. Same firm as Marcus Delaney.",
    outlook_history: "No Outlook history found.",
    linkedin_url: "https://www.linkedin.com",
    last_contact_date: isoDaysAgo(120),
    other_contacts_at_firm: "1 other: Marcus Delaney",
    state: {
      recruiter_id: "rr-005",
      status: "sent",
      starred: false,
      updated_at: isoDaysAgo(10),
    },
    notes: [],
    touches: [
      {
        id: "t-005",
        recruiter_id: "rr-005",
        channel: "linkedin",
        direction: "outbound",
        body: "Sent low-touch reconnect.",
        created_at: isoDaysAgo(10),
      },
    ],
  },
  {
    id: "rr-006",
    name: "Priya Raman",
    firm: "Korn Ferry",
    title: "Principal",
    specialty: "Consumer and B2B marketing",
    source: "Outlook (new)",
    tier: "TIER 4",
    strategic_score: 74,
    firm_fit_score: 76,
    practice_match_score: 70,
    recency_score: 65,
    signal_score: 68,
    strategic_recommended_approach:
      "Archive for now unless she appears on a live search. Relationship value is secondary to Amanda Kor at the same firm.",
    summary_of_prior_comms: "Light email history from 2024. No active search context.",
    outlook_history: "One response in 2024; no thread since.",
    last_contact_date: isoDaysAgo(210),
    other_contacts_at_firm: "2 others: Amanda Kor, Malik Stone",
    state: {
      recruiter_id: "rr-006",
      status: "snoozed",
      next_action_due_date: isoDaysFromNow(3),
      starred: false,
      updated_at: isoDaysAgo(4),
    },
    notes: [],
    touches: [],
  },
];
